services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      network: host
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    ports:
      - "${WEB_PORT:-8085}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-monitoring_ppa}
      MYSQL_USER: ${DB_USERNAME:-monitoring}
      MYSQL_PASSWORD: ${DB_PASSWORD:-monitoring}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - monitoring_ppa_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  monitoring_ppa_db_data:

